# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Login'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 540)
        Dialog.setMinimumSize(QtCore.QSize(540, 540))
        Dialog.setMaximumSize(QtCore.QSize(540, 540))
        Dialog.setBaseSize(QtCore.QSize(900, 1600))
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 50, 451, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/icon.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Enter = QtWidgets.QPushButton(Dialog)
        self.Enter.setGeometry(QtCore.QRect(180, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        self.Enter.setFont(font)
        self.Enter.setAutoFillBackground(False)
        self.Enter.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Enter.setDefault(True)
        self.Enter.setObjectName("Enter")
        self.UserName_text = QtWidgets.QLineEdit(Dialog)
        self.UserName_text.setGeometry(QtCore.QRect(180, 290, 271, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.UserName_text.setFont(font)
        self.UserName_text.setObjectName("UserName_text")
        self.Password_text = QtWidgets.QLineEdit(Dialog)
        self.Password_text.setGeometry(QtCore.QRect(180, 360, 271, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.Password_text.setFont(font)
        self.Password_text.setObjectName("Password_text")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Log-in"))
        self.Enter.setText(_translate("Dialog", "登入"))
        self.label_3.setText(_translate("Dialog", "UserName"))
        self.label_4.setText(_translate("Dialog", "Passwrod"))
